"""empty message

Revision ID: 93e5676da276
Revises: 
Create Date: 2019-06-09 08:12:56.751737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e5676da276'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('help', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('organization', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vulns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.Column('fix_describe', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('fix_date', sa.Date(), nullable=True),
    sa.Column('organization', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('annex', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulns_fix_date'), 'vulns', ['fix_date'], unique=False)
    op.create_index(op.f('ix_vulns_publish_date'), 'vulns', ['publish_date'], unique=False)
    op.create_index(op.f('ix_vulns_status'), 'vulns', ['status'], unique=False)
    op.create_index(op.f('ix_vulns_title'), 'vulns', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulns_title'), table_name='vulns')
    op.drop_index(op.f('ix_vulns_status'), table_name='vulns')
    op.drop_index(op.f('ix_vulns_publish_date'), table_name='vulns')
    op.drop_index(op.f('ix_vulns_fix_date'), table_name='vulns')
    op.drop_table('vulns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('platform_info')
    # ### end Alembic commands ###
